name: Minecraft Server 1.21.5

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  run-mc-server:
    runs-on: ubuntu-latest
    timeout-minutes: 305   # Max runtime ~5 hours

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install jq (JSON parser)
      run: sudo apt-get update && sudo apt-get install -y jq curl

    - name: Download Minecraft Server (Paper 1.21.5 latest build)
      run: |
        mkdir -p mc-server
        cd mc-server
        # Get latest Paper build for 1.21.5
        LATEST_BUILD=$(curl -s https://api.papermc.io/v2/projects/paper/versions/1.21.5 | jq -r '.builds[-1]')
        rm server.jar
        curl -o server.jar https://api.papermc.io/v2/projects/paper/versions/1.21.5/builds/$LATEST_BUILD/downloads/paper-1.21.5-$LATEST_BUILD.jar
        echo "eula=true" > eula.txt
        echo "online-mode=false" >> server.properties

    - name: Start Minecraft Server
  run: |
    cd mc-server
    timeout 50 java -Xms8G -Xmx14G -jar server.jar nogui
        
    - name: Restart Workflow
      if: ${{ always() }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Minecraft Server 1.21.5
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
