name: Minecraft Server 1.21.5

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  run-mc-server:
    runs-on: ubuntu-latest
    timeout-minutes: 305

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install utilities
      run: sudo apt-get update && sudo apt-get install -y jq curl wget unzip docker-compose

    - name: Create docker-compose.yml (Playit agent)
      run: |
        cat > docker-compose.yml <<'EOF'
        version: '3'
        services:
          playit:
            image: ghcr.io/playit-cloud/playit-agent:0.15
            container_name: playit
            restart: unless-stopped
            network_mode: host
            environment:
              - SECRET_KEY=942d4b95533c47f21962214c3dbadf68ecb82c65f8ff033fcb92077d6392f638
        EOF

    - name: Start Playit agent
      run: docker-compose up -d

    - name: Download previous server data (if exists)
      uses: actions/download-artifact@v4
      with:
        name: mc-server-data
        path: mc-server
      continue-on-error: true

    - name: Download Minecraft Server (Paper 1.21.5 latest build if missing)
      run: |
        mkdir -p mc-server
        cd mc-server
        if [ ! -f server.jar ]; then
          LATEST_BUILD=$(curl -s https://api.papermc.io/v2/projects/paper/versions/1.21.5 | jq -r '.builds[-1]')
          curl -o server.jar https://api.papermc.io/v2/projects/paper/versions/1.21.5/builds/$LATEST_BUILD/downloads/paper-1.21.5-$LATEST_BUILD.jar
          echo "eula=true" > eula.txt
          echo "online-mode=false" >> server.properties
          mkdir -p plugins
          cd plugins
          wget https://github.com/playit-cloud/playit-minecraft-plugin/releases/latest/download/playit-minecraft-plugin.jar
        else
          echo "Server files already exist, skipping download"
        fi

    - name: Start Minecraft Server (300s then stop)
      run: |
        cd mc-server
        nohup java -Xms8G -Xmx14G -jar server.jar nogui > server.log 2>&1 &
        sleep 250
        pkill -f java

    - name: Save full Minecraft Server data
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: mc-server-data
        path: mc-server

    - name: Restart Workflow
      if: ${{ always() }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Minecraft Server 1.21.5
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
