name: Minecraft Server 1.21.5

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  run-mc-server:
    runs-on: ubuntu-latest
    timeout-minutes: 305

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install utilities
      run: sudo apt-get update && sudo apt-get install -y jq curl wget

    - name: Download Minecraft Server (Paper 1.21.5 latest build)
      run: |
        mkdir -p mc-server
        cd mc-server
        LATEST_BUILD=$(curl -s https://api.papermc.io/v2/projects/paper/versions/1.21.5 | jq -r '.builds[-1]')
        curl -o server.jar https://api.papermc.io/v2/projects/paper/versions/1.21.5/builds/$LATEST_BUILD/downloads/paper-1.21.5-$LATEST_BUILD.jar
        echo "eula=true" > eula.txt
        echo "online-mode=false" >> server.properties
        mkdir -p plugins
        cd plugins
        wget https://github.com/playit-cloud/playit-minecraft-plugin/releases/latest/download/playit-minecraft-plugin.jar

    - name: Start Minecraft Server (300s then stop)
      run: |
        cd mc-server
        # Start server in background
        nohup java -Xms8G -Xmx14G -jar server.jar nogui &
        SERVER_PID=$!
        sleep 5
        # Give server time to start and op the player
        echo "op ks_warrior" > temp-op-command.txt
        cat temp-op-command.txt | nc localhost 25565 || true
        rm temp-op-command.txt
        # Stop server automatically after 300s
        sleep 18000
        kill $SERVER_PID

    - name: Restart Workflow
      if: ${{ always() }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Minecraft Server 1.21.5
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
