name: Dark Core SMP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  actions: write
  contents: write  # Needed to commit changes

concurrency:
  group: mc-server
  cancel-in-progress: true

jobs:
  run-mc-server:
    runs-on: ubuntu-latest
    timeout-minutes: 305

    steps:
    # --- Checkout repo ---
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- Java setup ---
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # --- Required tools ---
    - name: Install utilities
      run: sudo apt-get update && sudo apt-get install -y jq curl unzip docker-compose git

    # --- Setup Playit (Docker) ---
    - name: Create docker-compose.yml (Playit agent)
      run: |
        cat > docker-compose.yml <<'EOF'
        version: '3'
        services:
          playit:
            image: ghcr.io/playit-cloud/playit-agent:0.15
            container_name: playit
            restart: unless-stopped
            network_mode: host
            environment:
              - SECRET_KEY=942d4b95533c47f21962214c3dbadf68ecb82c65f8ff033fcb92077d6392f638
        EOF

    - name: Start Playit agent
      run: docker-compose up -d

    # --- Restore old server data ---
    - name: Pull latest Minecraft server data
      if: ${{ always() }}
      run: |
        git fetch origin main
        git checkout origin/main -- smp-data
        echo "Latest server data restored."
        ls

    # --- Setup Paper server ---
    - name: Prepare Minecraft Server
      run: |
        mkdir -p smp-data/plugins
        cd smp-data
        # Always refresh Paper build if missing
        if [ ! -f server.jar ]; then
          LATEST_BUILD=$(curl -s https://api.papermc.io/v2/projects/paper/versions/1.21.5 | jq -r '.builds[-1]')
          curl -L -o server.jar https://api.papermc.io/v2/projects/paper/versions/1.21.5/builds/$LATEST_BUILD/downloads/paper-1.21.5-$LATEST_BUILD.jar
          echo "eula=true" > eula.txt
        fi
        # Ensure server.properties exists & set offline mode
        if [ ! -f server.properties ]; then
          echo "online-mode=false" > server.properties
        else
          sed -i 's/^online-mode=.*/online-mode=false/' server.properties
        fi

    # --- Run Minecraft server ---
    - name: Start Minecraft Server (5 hours then stop)
      run: |
        cd smp-data
        echo "Starting Minecraft server..."
        timeout 300m java -Xms8G -Xmx14G -jar server.jar nogui
        
    # --- Commit & push server data back to repo ---
    - name: Commit Minecraft server data
      if: ${{ always() }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add smp-data
        git commit -m "Update Minecraft server data"
        git push origin main || echo "Nothing to commit"

    # --- Auto-restart workflow ---
    - name: Restart Workflow
      if: ${{ always() }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Dark Core SMP
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
